export const FETCH_USER_DETAILS='FETCH_USER_DETAILS';
export const DELETE_USER='DELETE_USER';
export const FETCH_USER_DETAILS_ERROR='FETCH_USER_DETAILS_ERRROR';
export const DELETE_USER_ERROR='DELETE_USER_ERROR';
export const FETCH_USER_DETAILS_START='FETCH_USER_DETAILS_START';
